# Change these first
owner: ahurtaud # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Plex
    url: http://plex.hurtauda.fr/identity
    icon: https://app.plex.tv/auth/favicon.ico
  - name: Grafana
    url: https://grafana.hurtauda.fr
    icon: https://grafana.hurtauda.fr/public/img/grafana_icon.svg
  - name: NAS
    url: https://nas.hurtauda.fr
  - name: TVHeadEnd
    url: https://$BASIC_AUTH@tv.hurtauda.fr
    icon: https://tv.hurtauda.fr/static/img/logo.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.hurtauda.fr
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Bienvenue sur le site de status pour les services proposés par **hurtauda.fr**."
  introMessage: "Veuillez retrouver ci-dessus le status pour chaque service"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
